spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5436}/${DB_NAME:ecommerce}
spring.datasource.username=${DB_USERNAME:ecommerce}
spring.datasource.password=${DB_PASSWORD:ecommerce}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT:6380}

spring.kafka.bootstrap-servers=localhost:${KAFKA_PORT:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ecommerce.backend.event
spring.kafka.consumer.auto-offset-reset=earliest

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

logging.level.com.ecommerce.backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG
